<?php

namespace App\Models;

use App\Traits\BelongsToSchool;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class SecurityReport extends Model
{
    use BelongsToSchool, HasFactory;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'teacher_id',
        'school_id',
        'generated_by',
        'file_path',
        'file_name',
        'risk_level',
        'date_range',
        'summary_data',
        'generation_type',
        'report_period_start',
        'report_period_end',
    ];

    /**
     * The attributes that should be cast.
     */
    protected $casts = [
        'summary_data' => 'array',
        'report_period_start' => 'datetime',
        'report_period_end' => 'datetime',
    ];

    /**
     * Risk level constants.
     */
    public const RISK_LOW = 'low';

    public const RISK_MEDIUM = 'medium';

    public const RISK_HIGH = 'high';

    public const RISK_CRITICAL = 'critical';

    /**
     * Generation type constants.
     */
    public const GENERATION_MANUAL = 'manual';

    public const GENERATION_AUTO = 'auto';

    /**
     * Get the teacher that this report is about.
     */
    public function teacher(): BelongsTo
    {
        return $this->belongsTo(User::class, 'teacher_id');
    }

    /**
     * Get the school this report belongs to.
     */
    public function school(): BelongsTo
    {
        return $this->belongsTo(School::class);
    }

    /**
     * Get the user who generated this report.
     */
    public function generator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    /**
     * Scope to filter by risk level.
     */
    public function scopeByRiskLevel($query, string $level)
    {
        return $query->where('risk_level', $level);
    }

    /**
     * Scope to filter critical risk reports.
     */
    public function scopeCritical($query)
    {
        return $query->where('risk_level', self::RISK_CRITICAL);
    }

    /**
     * Scope to filter by teacher.
     */
    public function scopeForTeacher($query, int $teacherId)
    {
        return $query->where('teacher_id', $teacherId);
    }

    /**
     * Scope to filter by generator.
     */
    public function scopeGeneratedBy($query, int $userId)
    {
        return $query->where('generated_by', $userId);
    }

    /**
     * Scope for auto-generated reports.
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('generation_type', self::GENERATION_AUTO);
    }

    /**
     * Get full path to the PDF file.
     */
    public function getFullPathAttribute(): string
    {
        return storage_path('app/'.$this->file_path);
    }

    /**
     * Check if file exists.
     */
    public function fileExists(): bool
    {
        return file_exists($this->full_path);
    }

    /**
     * Get risk level badge color.
     */
    public function getRiskColorAttribute(): string
    {
        return match ($this->risk_level) {
            self::RISK_CRITICAL => '#dc2626', // red-600
            self::RISK_HIGH => '#ea580c',     // orange-600
            self::RISK_MEDIUM => '#ca8a04',   // yellow-600
            self::RISK_LOW => '#16a34a',      // green-600
            default => '#6b7280',             // gray-500
        };
    }

    /**
     * Get risk level label.
     */
    public function getRiskLabelAttribute(): string
    {
        return match ($this->risk_level) {
            self::RISK_CRITICAL => 'CRITICAL',
            self::RISK_HIGH => 'HIGH',
            self::RISK_MEDIUM => 'MEDIUM',
            self::RISK_LOW => 'LOW',
            default => 'UNKNOWN',
        };
    }
}
