<?php

namespace App\Services;

use App\Models\StudentCard;
use App\Models\User;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class StudentCardService
{
    public function generateCard(User $student, User $admin): StudentCard
    {
        StudentCard::where('student_id', $student->id)
            ->where('is_active', true)
            ->update(['is_active' => false, 'revoked_at' => now(), 'revoked_reason' => 'Regenerated by admin']);

        $qrHash = hash_hmac('sha256', Str::random(32) . $student->id . now(), config('app.key'));
        $card = StudentCard::create([
            'student_id' => $student->id,
            'qr_hash' => $qrHash,
            'issued_by' => $admin->id,
            'issued_at' => now(),
            'is_active' => true,
        ]);

        Log::channel('audit')->info('student_card_generated', [
            'admin_id' => $admin->id,
            'student_id' => $student->id,
            'card_id' => $card->id,
            'timestamp' => now(),
        ]);

        return $card;
    }

    public function markDistributed(StudentCard $card, User $admin): StudentCard
    {
        $card->update([
            'distributed_at' => now(),
            'distributed_by' => $admin->id,
        ]);
        Log::channel('audit')->info('student_card_distributed', [
            'admin_id' => $admin->id,
            'student_id' => $card->student_id,
            'card_id' => $card->id,
            'timestamp' => now(),
        ]);
        return $card;
    }

    public function regenerateCard(User $student, User $admin, string $reason): StudentCard
    {
        $oldCard = StudentCard::where('student_id', $student->id)
            ->where('is_active', true)
            ->first();
        if ($oldCard) {
            $oldCard->update([
                'is_active' => false,
                'revoked_at' => now(),
                'revoked_reason' => $reason,
            ]);
            Log::channel('audit')->info('student_card_revoked', [
                'admin_id' => $admin->id,
                'student_id' => $student->id,
                'card_id' => $oldCard->id,
                'timestamp' => now(),
                'reason' => $reason,
            ]);
        }
        $newCard = $this->generateCard($student, $admin);
        Log::channel('audit')->info('student_card_regenerated', [
            'admin_id' => $admin->id,
            'student_id' => $student->id,
            'card_id' => $newCard->id,
            'timestamp' => now(),
            'reason' => $reason,
        ]);
        return $newCard;
    }

    public function validateCard(User $student, string $qrHash): bool
    {
        $card = StudentCard::where('student_id', $student->id)
            ->where('is_active', true)
            ->first();
        if (!$card || $card->qr_hash !== $qrHash) {
            return false;
        }
        if ($card->revoked_at || !$card->is_active) {
            return false;
        }
        return true;
    }

    public function getCardHistory(User $student)
    {
        return StudentCard::where('student_id', $student->id)
            ->orderByDesc('issued_at')
            ->get();
    }

    public function bulkGenerateCards($students, $admin, $forceRegenerate, $filters, $isQueue = false)
    {
        $total = 0;
        $generated = 0;
        $skipped = 0;
        $regenerated = 0;
        foreach ($students as $student) {
            $total++;
            $activeCard = StudentCard::where('student_id', $student->id)->where('is_active', true)->first();
            if ($activeCard) {
                if (!$forceRegenerate) {
                    $skipped++;
                    continue;
                }
                $this->regenerateCard($student, $admin, 'Bulk regenerate');
                $regenerated++;
            } else {
                $this->generateCard($student, $admin);
                $generated++;
            }
            // TODO: Generate PDF for each student using student-card.blade.php
        }
        // TODO: Zip all PDFs and store temporarily, return path if not queue
        Log::channel('audit')->info('bulk_student_card_generation', [
            'admin_id' => $admin->id,
            'filters_used' => $filters,
            'total_students' => $total,
            'generated_count' => $generated,
            'regenerated_count' => $regenerated,
            'skipped_count' => $skipped,
            'timestamp' => now(),
            'is_queue' => $isQueue,
        ]);
        return [
            'total_students_processed' => $total,
            'cards_generated' => $generated,
            'cards_skipped' => $skipped,
            'cards_regenerated' => $regenerated,
        ];
    }

    public function ensurePhotoApproved(User $student)
    {
        if ($student->photo_review_status !== 'approved') {
            abort(422, 'Foto siswa belum disetujui admin. Tidak dapat mencetak kartu.');
        }
    }
}
