<?php

namespace App\Services;

use App\Models\StudentCard;
use App\Models\User;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class StudentCardService
{
    public function generateCard(User $student, User $admin): array
    {
        StudentCard::where('student_id', $student->id)
            ->where('is_active', true)
            ->update(['is_active' => false, 'revoked_at' => now(), 'revoked_reason' => 'Regenerated by admin']);

        $plainToken = Str::random(40);
        $qrHash = hash_hmac('sha256', $plainToken, config('app.key'));

        $card = StudentCard::create([
            'student_id' => $student->id,
            'school_id' => $student->school_id ?? $admin->school_id,
            'qr_hash' => $qrHash,
            'qr_token_encrypted' => $plainToken, // Automatically encrypted by model cast
            'issued_by' => $admin->id,
            'issued_at' => now(),
            'is_active' => true,
        ]);

        Log::channel('audit')->info('student_card_generated', [
            'admin_id' => $admin->id,
            'student_id' => $student->id,
            'card_id' => $card->id,
            'school_id' => $card->school_id,
            'timestamp' => now(),
        ]);

        return [
            'card' => $card,
            'plain_token' => $plainToken,
            'qr_string' => $card->id.'|'.$plainToken,
        ];
    }

    public function markDistributed(StudentCard $card, User $admin): StudentCard
    {
        $card->update([
            'distributed_at' => now(),
            'distributed_by' => $admin->id,
        ]);
        Log::channel('audit')->info('student_card_distributed', [
            'admin_id' => $admin->id,
            'student_id' => $card->student_id,
            'card_id' => $card->id,
            'timestamp' => now(),
        ]);

        return $card;
    }

    public function regenerateCard(User $student, User $admin, string $reason): array
    {
        $oldCard = StudentCard::where('student_id', $student->id)
            ->where('is_active', true)
            ->first();
        if ($oldCard) {
            $oldCard->update([
                'is_active' => false,
                'revoked_at' => now(),
                'revoked_reason' => $reason,
            ]);
            Log::channel('audit')->info('student_card_revoked', [
                'admin_id' => $admin->id,
                'student_id' => $student->id,
                'card_id' => $oldCard->id,
                'timestamp' => now(),
                'reason' => $reason,
            ]);
        }
        $result = $this->generateCard($student, $admin);

        Log::channel('audit')->info('student_card_regenerated', [
            'admin_id' => $admin->id,
            'student_id' => $student->id,
            'card_id' => $result['card']->id,
            'timestamp' => now(),
            'reason' => $reason,
        ]);

        return $result;
    }

    public function validateCard(User $student, string $plainToken): bool
    {
        $card = StudentCard::where('student_id', $student->id)
            ->where('is_active', true)
            ->first();

        if (! $card) {
            return false;
        }

        // Verify HMAC
        $expectedHash = hash_hmac('sha256', $plainToken, config('app.key'));

        if (! hash_equals($card->qr_hash, $expectedHash)) {
            return false;
        }

        if ($card->revoked_at || ! $card->is_active) {
            return false;
        }

        return true;
    }

    public function getCardHistory(User $student)
    {
        return StudentCard::where('student_id', $student->id)
            ->orderByDesc('issued_at')
            ->get();
    }

    public function bulkGenerateCards($students, $admin, $forceRegenerate, $filters, $isQueue = false, callable $onProgress = null)
    {
        $total = 0;
        $generated = 0;
        $skipped = 0;
        $regenerated = 0;
        $pdfPaths = [];
        $studentCount = $students->count();

        $qrAvailable = class_exists('\\SimpleSoftwareIO\\QrCode\\Facades\\QrCode');

        foreach ($students as $student) {
            $total++;
            if ($onProgress) {
                $onProgress($total, $studentCount);
            }
            $activeCard = StudentCard::where('student_id', $student->id)->where('is_active', true)->first();
            if ($activeCard) {
                if (! $forceRegenerate) {
                    $skipped++;
                    continue;
                }
                $this->regenerateCard($student, $admin, 'Bulk regenerate');
                $regenerated++;
            } else {
                $this->generateCard($student, $admin);
                $generated++;
            }

            // Generate PDF for each student (skip if QR package not available)
            if ($qrAvailable) {
                try {
                    $card = StudentCard::where('student_id', $student->id)->where('is_active', true)->first();
                    if ($card) {
                        $token = $card->qr_token_encrypted;
                        $qrCode = \SimpleSoftwareIO\QrCode\Facades\QrCode::format('png')->size(200)->generate($token);
                        $qrBase64 = 'data:image/png;base64,' . base64_encode($qrCode);

                        $pdf = \Barryvdh\DomPDF\Facade\Pdf::loadView('pdf.student-card', [
                            'student' => $student,
                            'qrCode' => $qrBase64,
                            'card' => $card,
                            'school' => $student->school
                        ]);

                        $filename = 'card_' . preg_replace('/[^a-zA-Z0-9]/', '_', $student->name) . '_' . $student->nis . '.pdf';
                        $path = 'temp/cards/' . $filename;
                        \Illuminate\Support\Facades\Storage::put($path, $pdf->output());
                        $pdfPaths[] = $path;
                    }
                } catch (\Exception $e) {
                    Log::warning('PDF generation skipped for student ' . $student->id . ': ' . $e->getMessage());
                }
            }
        }

        $zipFileName = null;
        // Create Zip archive only if PDFs were generated
        if (!empty($pdfPaths)) {
            $zipFileName = 'student_cards_batch_' . now()->format('Ymd_His') . '.zip';
            $zipPath = storage_path('app/temp/' . $zipFileName);

            if (!file_exists(dirname($zipPath))) {
                mkdir(dirname($zipPath), 0755, true);
            }

            $zip = new \ZipArchive;
            if ($zip->open($zipPath, \ZipArchive::CREATE | \ZipArchive::OVERWRITE) === true) {
                foreach ($pdfPaths as $pdfFile) {
                    if (\Illuminate\Support\Facades\Storage::exists($pdfFile)) {
                        $zip->addFile(storage_path('app/' . $pdfFile), basename($pdfFile));
                    }
                }
                $zip->close();
                \Illuminate\Support\Facades\Storage::delete($pdfPaths);
            } else {
                Log::error('Failed to create ZIP archive for student cards');
                $zipFileName = null;
            }
        }

        Log::channel('audit')->info('bulk_student_card_generation', [
            'admin_id' => $admin->id,
            'filters_used' => $filters,
            'total_students' => $total,
            'generated_count' => $generated,
            'regenerated_count' => $regenerated,
            'skipped_count' => $skipped,
            'timestamp' => now(),
            'is_queue' => $isQueue,
        ]);

        return [
            'total_students_processed' => $total,
            'cards_generated' => $generated,
            'cards_skipped' => $skipped,
            'cards_regenerated' => $regenerated,
            'zip_path' => $zipFileName,
            'pdf_generated' => !empty($pdfPaths),
        ];
    }

    public function deactivateCard(User $student, User $admin, string $reason = 'Deactivated by admin'): bool
    {
        $card = StudentCard::where('student_id', $student->id)
            ->where('is_active', true)
            ->first();

        if (! $card) {
            return false;
        }

        $card->update([
            'is_active' => false,
            'revoked_at' => now(),
            'revoked_reason' => $reason,
        ]);

        Log::channel('audit')->info('student_card_deactivated', [
            'admin_id' => $admin->id,
            'student_id' => $student->id,
            'card_id' => $card->id,
            'timestamp' => now(),
            'reason' => $reason,
        ]);

        return true;
    }

    public function getCardStatus(User $student)
    {
        $card = StudentCard::where('student_id', $student->id)
            ->where('is_active', true)
            ->first();

        if (! $card) {
            return [
                'has_active_card' => false,
                'status' => 'no_card',
            ];
        }

        return [
            'has_active_card' => true,
            'card_id' => $card->id,
            'issued_at' => $card->issued_at,
            'distributed_at' => $card->distributed_at,
            'status' => $card->distributed_at ? 'active_distributed' : 'active_not_distributed',
        ];
    }
}
