<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Convert the legacy enum CHECK constraint on attendances.status
     * into a plain string column.
     *
     * The state machine writes 'pending' and 'rejected' into the legacy
     * status field (syncLegacyStatus), which violates the PostgreSQL
     * CHECK constraint generated by the original enum column.
     */
    public function up(): void
    {
        Schema::table('attendances', function (Blueprint $table) {
            $table->string('status', 20)->change();
        });

// PostgreSQL keeps the CHECK constraint generated by the original
        // enum column after ALTER TYPE - drop it explicitly. SQLite does not
        // support DROP CONSTRAINT, and its column rebuild handles the check.
        if (Schema::getConnection()->getDriverName() === 'pgsql') {
            \Illuminate\Support\Facades\DB::statement(
                'ALTER TABLE attendances DROP CONSTRAINT IF EXISTS attendances_status_check'
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('attendances', function (Blueprint $table) {
            $table->enum('status', ['present', 'late', 'absent', 'sick', 'permit', 'excused'])->change();
        });
    }
};
