<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Convert the legacy enum CHECK constraint on attendance_logs.action
     * into a plain string column.
     *
     * The state machine writes 'state_transition' as the action value,
     * which violates the PostgreSQL CHECK constraint generated by the
     * original enum column.
     */
    public function up(): void
    {
        Schema::table('attendance_logs', function (Blueprint $table) {
            $table->string('action', 50)->change();
        });

        if (Schema::getConnection()->getDriverName() === 'pgsql') {
            DB::statement(
                'ALTER TABLE attendance_logs DROP CONSTRAINT IF EXISTS attendance_logs_action_check'
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('attendance_logs', function (Blueprint $table) {
            $table->enum('action', ['scan_in', 'scan_out', 'manual_create', 'manual_update', 'approve', 'reject'])->change();
        });
    }
};
